<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard Summary</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 20px;
        }
        h1, h2 {
            text-align: center;
        }
        .info {
            margin-top: 20px;
        }
        .info p {
            margin: 5px 0;
            font-size: 14px;
        }
        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
            font-size: 14px;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #000;
        }
        th {
            background-color: #f0f0f0;
        }
        footer {
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: gray;
        }
    </style>
</head>
<body>

    <h1>Grade Tracker Report</h1>
    <h2>{{ Auth::user()->name }}</h2>

    <div class="info">
        <p><strong>Generated on:</strong> {{ now()->format('d M Y') }}</p>
        <p><strong>CGPA:</strong> {{ number_format($gpa, 2) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Subject</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach($grades as $grade)
                <tr>
                    <td>{{ $grade->subject }}</td>
                    <td>{{ $grade->grade }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        Generated by Grade Tracker System
    </footer>

</body>
</html>
